version: '3'
services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - MONGO_URI=${MONGO_URI} 
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${BACKEND_PORT}
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
